spring.application.name=Kappa-Stock-BackEnd


spring.data.mongodb.uri=mongodb+srv://manuelguarnizog_db_user:slmEouXGl5LaTDbg@clustereciexpress.m7ljcsf.mongodb.net/?appName=ClusterECIEXPRESS
spring.data.mongodb.database=stock-management-db

server.port=8087
