name: CD - Deploy Stock Backend (Dev)

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_NAME="${{ secrets.ACR_LOGIN_SERVER }}/stock-service"
          GIT_TAG=${GITHUB_SHA::7}
          docker build -t "$IMAGE_NAME:latest" -t "$IMAGE_NAME:$GIT_TAG" .

      - name: Push Docker image to ACR
        run: |
          IMAGE_NAME=${{ secrets.ACR_LOGIN_SERVER }}/stock-service
          GIT_TAG=${GITHUB_SHA::7}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$GIT_TAG

      - name: Deploy container to Azure Web App (DEV)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_STOCK_NAME_DEV }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_STOCK_PUBLISH_DEV }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/stock-service:latest
