name: CI - Tests and Quality (Stock)

on:
  push:
    branches:
      - develop
      - main
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - main
      - 'feature/**'

jobs:
  test-and-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build + Test + Coverage
        run: mvn -B clean verify
        env:
          SPRING_PROFILES_ACTIVE: test
      #Needs fixing
      #- name: SonarQube Analysis
      #  run: |
      #    mvn -B sonar:sonar \
      #    -Dsonar.projectKey=Kappa-Stock-BackEnd \
      #    -Dsonar.organization=ECIXPRESS \
      #    -Dsonar.host.url=https://sonarcloud.io \
      #    -Dsonar.login=${{ secrets.SONAR_TOKEN }}


      - name: Publish JaCoCo HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          if-no-files-found: ignore
